--- 
development: !map:HashWithIndifferentAccess 
  plugins: greyresults, inflector, jquery.formbouncer, jquery.hinty, jquery.iframe
  theme: storagelocator
  title: US Self Storage Locator
  widgets: anim2
  description: ""
  keywords: ""
production: 
    plugins: greyresults, inflector, jquery.formbouncer, jquery.hinty, jquery.iframe
    theme: storagelocator
    title: US Self Storage Locator
    widgets: anim2
    description: ""
    keywords: ""
test: 
  plugins: inflector, jquery.formbouncer, jquery.hinty, jquery.iframe
  title: US Self Storage Locator
  theme: storagelocator
  widgets: anim2
  description: 
  keywords: 
