--- 
development: !map:HashWithIndifferentAccess 
  plugins: inflector, jquery.formbouncer, jquery.hinty, jquery.iframe, jsAnim
  theme: storagelocator
  title: US Self Storage Locator
  widgets: anim2
  description: ""
  keywords: ""
production: 
  plugins: inflector, jquery.formbouncer, jquery.hinty, jquery.iframe
  theme: storagelocator
  title: US Self Storage Locator
  widgets: anim2
  description: 
  keywords: 
test: 
  plugins: inflector, jquery.formbouncer, jquery.hinty, jquery.iframe
  theme: storagelocator
  title: US Self Storage Locator
  widgets: anim2
  description: 
  keywords: 
